// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvK9hCDnlSaLSlMal3M_rUGewz3hLJ88',
    appId: '1:45472281587:web:6f6b4a1b8c34e0c5cd9886',
    messagingSenderId: '45472281587',
    projectId: 'water-heater-5999f',
    authDomain: 'water-heater-5999f.firebaseapp.com',
    databaseURL: 'https://water-heater-5999f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-heater-5999f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu16LlzurDIq6-TAwYz16ZL2QchgtLdrA',
    appId: '1:45472281587:android:c4f5466ac6f45cf6cd9886',
    messagingSenderId: '45472281587',
    projectId: 'water-heater-5999f',
    databaseURL: 'https://water-heater-5999f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-heater-5999f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe75UnmdfN2K2fLb632j4YWkdrLex21dk',
    appId: '1:45472281587:ios:b67e2a0cecd4debbcd9886',
    messagingSenderId: '45472281587',
    projectId: 'water-heater-5999f',
    databaseURL: 'https://water-heater-5999f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-heater-5999f.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe75UnmdfN2K2fLb632j4YWkdrLex21dk',
    appId: '1:45472281587:ios:b67e2a0cecd4debbcd9886',
    messagingSenderId: '45472281587',
    projectId: 'water-heater-5999f',
    databaseURL: 'https://water-heater-5999f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-heater-5999f.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgvK9hCDnlSaLSlMal3M_rUGewz3hLJ88',
    appId: '1:45472281587:web:bb519ccc59fc2be8cd9886',
    messagingSenderId: '45472281587',
    projectId: 'water-heater-5999f',
    authDomain: 'water-heater-5999f.firebaseapp.com',
    databaseURL: 'https://water-heater-5999f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-heater-5999f.firebasestorage.app',
  );
}
